markdown:         rdiscount
pygments:         true
paginate:         6
permalink: /:year/:month/:title.html

title:            "Li Jingui's Workspace"
url:              http://lijingui.github.com
feed:             /atom.xml
author:
    name:         Jingui Li
    email:        buaa.lijingui@gmail.com
    skype:        

description:      "工作内容整理"
about: 			 		  ""
follow:
    github:       https://github.com/nourlcn
    twitter:      https://twitter.com/nourlcn
style: 			  /css/style.css
blogName: 		  Li Jingui's Workspace
blogDesc: 		  工作涉及：大数据、电子政务、信息化.
